### PR TITLE
DEVX-2686: make null-safe reference to GITPOD_WORKSPACE_URL

### PR DESCRIPTION
**Pull request by javabrett**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2686

_What behavior does this PR change, and why?_

Fix this error when running `add-broker.sh` from SBC demo:

```
cp-demo/scripts/sbc/../env.sh: line 30: GITPOD_WORKSPACE_URL: unbound variable
```

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

 - [ ] Documentation
 - [X] Run cp-demo 

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Review by ybyzek — COMMENTED** [review]
@javabrett thanks for triaging and the quick turnaround.  I haven't validated the fix but based on what I read up on the error message, it seems to be a great fix.  

1. Please retarget and rebase to `6.2.0-post`, which is when GitPod was introduced into cp-demo
2. It would be good to get a second review from @chuck-confluent before merging.

**Comment by javabrett** [comment]
@ybyzek target branch changed to `6.2.0-post`.

**Comment by javabrett** [comment]
Tested local on MacOS and in GitPod, running `add-broker.sh`.

**Review by ybyzek — APPROVED** [review]
From Slack, sounds like @esakkiraj has validated this PR in his env, so we don't have to wait for @chuck-confluent .  @javabrett please merge at your convenience.

**Pull request merged**
