### PR TITLE
DEVX-2320: Allow users to opt-out of Elasticsearch and Kibana to reduce memory footprint

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-2320

_What behavior does this PR change, and why?_

Elasticsearch and Kibana are now opt-out:

* Allow option to reduce memory footprint of cp-demo for users who are memory constrained

Reasons to choose opt-out over opt-in:

* Viz is compelling to some users
* Default behavior (VIZ=true) is consistent with current behavior: continuity for existing users and no impact to jmx-monitoring-stacks (@jeanlouisboudart @waliaabhishek )
* Keeps Elasticsearch sink connector in main workflow: demonstrates & validates a sink connector
* Looking at Kibana dashboard simplifies smoke test to validate cp-demo is working after changes are made
* Smoother UX for future enhancements to visualizations added to cp-demo (cc: @robcowart )
* Simplifies docs

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Documentation: see https://github.com/confluentinc/docs-platform/pull/170 for staging server
- [x] Run cp-demo: both with default (`VIZ=true`) and `VIZ=false` 

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [ ] Documentation: see https://github.com/confluentinc/docs-platform/pull/170 for staging server
- [ ] Run cp-demo: both with default (`VIZ=false`) and `VIZ=true` 
- [ ] jmx-monitoring-stacks: @jeanlouisboudart @waliaabhishek

### CODE REVIEW

**Comment by jwfbean** [comment]
I'm imagining a world where we have swappable front ends. Can we call the variable something else, eg ES or ELASTIC?

**Comment by ybyzek** [comment]
> I'm imagining a world where we have swappable front ends. Can we call the variable something else, eg ES or ELASTIC?

@jwfbean  While it's not a far-fetched idea, there are no plans for to swap another frontend.  Even more so, if there were a thought to future-proof, one could imagine using Elasticsearch but a different Viz tool (e.g. Grafana instead of Kibana).  It doesn't make sense to enumerate those permutations at this time, so my leaning is to leave it generic as `VIZ` for now.

**Comment by jwfbean** [comment]
Does a cp-demo user ever want to use Elastic without Kibana? If yes, then `VIZ` is definitely a misnomer. If no, then yeah I agree it's fine.

**Comment by ybyzek** [comment]
> Does a cp-demo user ever want to use Elastic without Kibana? If yes, then `VIZ` is definitely a misnomer. If no, then yeah I agree it's fine.

@jwfbean to the best of my knowledge, I haven't heard of this use case.

**Review by javabrett — APPROVED** [review]

**Review by mikebin — APPROVED** [review]
LGTM

**Review by jeanlouisboudart — APPROVED** [review]
LGTM

**Pull request merged**
