### PR TITLE
DEVX-1591: Tighten up super users in cp-demo

### PR DESCRIPTION
**Pull request by ybyzek**

### CODE REVIEW

**Comment by rspurgeon** [comment]
@ybyzek I'm getting errors running on this branch (below), continuing to investigate

```
Waiting up to 60 seconds for MDS to start
...........................................................Failed after 60 attempts

Available LDAP users:
ERROR: No container found for openldap_1
Creating role bindings for principals

# Login
spawn confluent login --url http://kafka1:8091
Updates are available for confluent from (current: v0.251.0, latest: v0.252.0). To install them, please run:
$ confluent update

Enter your Confluent credentials:
Username: superUser
Password:

Error: Get http://kafka1:8091/security/1.0/authenticate: dial tcp 172.30.0.4:8091: connect: connection refused
Failed to log into MDS.  Please check all parameters and run again
```

**Comment by ybyzek** [comment]
@rspurgeon 

> ERROR: No container found for openldap_1

Something more basic is failing?

**Comment by rspurgeon** [comment]
the ldqp container is not starting with the following in the log:
```
openldap                       | ldap_add: Other (e.g., implementation specific) error (80)
openldap                       | modifying entry "cn=module{0},cn=config"
openldap                       |
openldap                       | adding new entry "olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config"
openldap                       |
openldap                       | ldap_modify: Insufficient access (50)
openldap                       | modifying entry "cn=module{0},cn=config"
openldap                       | *** /container/run/startup/slapd failed with status 50
openldap                       |
openldap                       | *** Run commands before finish...
openldap                       | *** Killing all processes...
openldap                       | 5e6a624b daemon: shutdown requested and initiated.
openldap                       | 5e6a624b slapd shutdown: waiting for 0 operations/tasks to finish
openldap                       | 5e6a624b slapd stopped.
```

**Comment by rspurgeon** [comment]
> the ldqp container is not starting with the following in the log:

This occurs even if I just try and start the openldap service on it's own w/ docker-compose up openldap

**Comment by ybyzek** [comment]
@rspurgeon I can't reproduce that and so far no one else has reported it.  Googling for it, I see one reference that maybe/sorta/possibly suggests a bad volume.  Can you try cleaning up the Docker resources on your host to see if it resolves the issue with the openLDAP container?

(Meanwhile, I filed a separate jira for tracking: cp-demo should fail fast if it doesn't come up)

**Comment by rspurgeon** [comment]
I cleaned out old volumes, containers and networks and indeed it worked after.

**Comment by ybyzek** [comment]
Thanks for confirming @rspurgeon .

(side bar: the fail fast PR is ready at https://github.com/confluentinc/cp-demo/pull/171)

**Pull request merged**
