### PR TITLE
DEVX-2256: Remove and replace deprecated configurations

### PR DESCRIPTION
**Pull request by rspurgeon**
### Description 
Removes or replaces deprecated configuraitons for SR, connect, and Kafka REST proxy.

_What behavior does this PR change, and why?_
In the case of key converters, the unecessary configurations are removed.  in the case of SSL client auth, the proper configuration is put in place of the deprecated name.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [X] Run cp-demo

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [ ] Run cp-demo

### CODE REVIEW

**Review by awalther28 — APPROVED** [review]
I validated this PR by running cp-demo. I checked that the schema registry config `ssl.client.authentication` was being set as expected to `NONE`.

**Review by mikebin — APPROVED** [review]
LGTM. Would it make sense to set the brokers' `ssl.client.auth=requested`, since SSL authN is only needed for the SSL listener, but not for the TOKEN listener?

**Review by ybyzek — APPROVED** [review]
@rspurgeon LGTM, thanks!

**Comment by rspurgeon** [comment]
> LGTM. Would it make sense to set the brokers' `ssl.client.auth=requested`, since SSL authN is only needed for the SSL listener, but not for the TOKEN listener?

@mikebin The latest has this change, can you please validate this is proper?  I'm not familiar with this area of the product.  Thank you

**Comment by ybyzek** [comment]
@rspurgeon I ran cp-demo with the latest and it works.

@mikebin for my education, if `SSL authN is only needed for the SSL listener, but not for the TOKEN listener`, then how did `required` work?  

Is it that:

1. `SSL authN` codepath was never invoked for the `TOKEN listener` anyway, or
2. `SSL authN` codepath was invoked for the `TOKEN listener` but it was redundant, or
3. I am missing another piece of the puzzle

**Comment by mikebin** [comment]
> Is it that:
SSL authN codepath was never invoked for the TOKEN listener anyway, or
SSL authN codepath was invoked for the TOKEN listener but it was redundant, or
I am missing another piece of the puzzle

**Pull request merged**
