### PR TITLE
DEVX-1368: cp-demo: revert running ksqlDB commands back to RUN SCRIPT

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

https://confluentinc.atlassian.net/browse/DEVX-1368

_What behavior does this PR change, and why?_

Run ksqlDB commands as RUN SCRIPT

With PR:

```
real    1m23.779s
user    0m0.534s
sys     0m0.097s
```

Without PR:

```
real    3m19.011s
user    0m0.639s
sys     0m0.132s
```

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Run cp-demo

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [ ] Run cp-demo

### CODE REVIEW

**Review by mikebin — APPROVED** [review]
LGTM

**Review by javabrett — APPROVED** [review]
Can remove:

```
docker-compose.yml:855:      - ./scripts/ksqlDB/run_ksqlDB_commands.sh:/tmp/run_ksqlDB_commands.sh
```

**Comment by ybyzek** [comment]
@javabrett great catch, thank you.  Now resolved.

**Review by rspurgeon — APPROVED** [review]
LGTM

**Pull request merged**
