### PR TITLE
Move security commands to Docker: #367

### PR DESCRIPTION
**Pull request by ybyzek**
### Description 

#367 

_What behavior does this PR change, and why?_

See issue for details, but the solution in this PR is to move the certificate creation commands to a Docker image, to remove dependency on Java version in host environment

Note, to validate this PR, it's essential to run the start script with `CLEAN=true`

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

- [x] Run cp-demo: as part of the validation, I downloaded Java v16 and verified that current cp-demo fails, then ran cp-demo with this PR and it passes.

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

- [x] Run cp-demo

### CODE REVIEW

**Comment by rspurgeon** [comment]
@ybyzek FYC, instead of adding another docker image definition, and docker-compose service to maintain (and another image for the user to pull down), WDYT about using the existing kafka image that we already have?  Mount a script and the volumes to a `docker run` for `cp-server:$CONFLUENT_DOCKER_TAG`.  Added benefit is we will use whatever version of Java the CP images have instead of any potential issue of hardcoding the java version 8 in the new local docker image definition.

**Comment by ybyzek** [comment]
> @ybyzek FYC, instead of adding another docker image definition, and docker-compose service to maintain (and another image for the user to pull down), WDYT about using the existing kafka image that we already have? Mount a script and the volumes to a `docker run` for `cp-server:$CONFLUENT_DOCKER_TAG`. Added benefit is we will use whatever version of Java the CP images have instead of any potential issue of hardcoding the java version 8 in the new local docker image definition.

@rspurgeon excellent suggestion!  I have implemented it in the latest version of this PR.

**Review by rspurgeon — APPROVED** [review]
LGTM 🥇 tested w/ a cp-demo run, all systems go

**Review by javabrett — APPROVED** [review]
OK with me.

Main downside is that whenever certs need (re)generation we have to pay for a `yum -y install findutils;` into a temp image - I guess that's worth it for consistency.  Not important for now, but I wonder if there's just some old regular image that already includes the right Java version and `find`.

**Comment by ybyzek** [comment]
@javabrett the cost of `yum -y install findutils` for a workflow that doesn't happen that often seems ok to incur, but just to document in the PR if needed for later, one alternative could be to build a local image using cp-server as the base, adding yum install, then saving that image locally for reuse

**Pull request merged**
